In [1]:
import pandas as pd
import numpy as np

In [2]:
def calculate_monthly_payment(P, T, r):
    '''Computes the monthly payment of Amortized loan

    Parameters
    ----------
    P : int
        Principal of the loan
    T : int
        Maturity of the loan in years
    r : float
        Nominal annual interest rate (value that reads on the contract)

    Amortized loan is formed by individual monthly payments,
    that are generating monthly interest,
    meaning that the total principal P is a sum of this geometrical series,
    where initial value a = A / (1 + r)^1
    https://www.investopedia.com/terms/a/amortization.asp
    https://teachingcalculus.com/2015/02/09/amortization/

    Nominal Yearly interest rate is compounded monthly -> r/12.
    '''
    t_months = T * 12
    r_monthly = r / 12
    A = P*r_monthly*(1 + r_monthly) ** t_months / ((1 + r_monthly) ** t_months - 1)
    return A

def generate_amortization_schedule(P, T ,r):
    yearly_payment = calculate_monthly_payment(P, T ,r)
    schedule = []
    balance = P
    for month in range(1, T*12 + 1):
        interest_payment = balance * (r/12)
        principal_payment = yearly_payment - interest_payment
        balance -= principal_payment
        schedule.append({
                'Year' : np.ceil(month/12).astype(int),
                'Month': month,
                'Payment' : yearly_payment,
                'Principal' : principal_payment,
                'Interest' : interest_payment,
                'Balance' : balance     
            })
    return pd.DataFrame(schedule).round(0)

In [3]:
P = 100_000
T = 10
r = 0.05
amortization_schedule = generate_amortization_schedule(P, T, r)

display(amortization_schedule)

     Year  Month  Payment  Principal  Interest  Balance
0       1      1   1061.0      644.0     417.0  99356.0
1       1      2   1061.0      647.0     414.0  98709.0
2       1      3   1061.0      649.0     411.0  98060.0
3       1      4   1061.0      652.0     409.0  97408.0
4       1      5   1061.0      655.0     406.0  96753.0
..    ...    ...      ...        ...       ...      ...
115    10    116   1061.0     1039.0      22.0   4199.0
116    10    117   1061.0     1043.0      17.0   3156.0
117    10    118   1061.0     1048.0      13.0   2108.0
118    10    119   1061.0     1052.0       9.0   1056.0
119    10    120   1061.0     1056.0       4.0     -0.0

[120 rows x 6 columns]

In [5]:
customdata=np.stack((np.ceil(amortization_schedule.index/12), (amortization_schedule['Balance'] / 1000)), axis=-1)

In [7]:
display(customdata[0])

array([ 0.   , 99.356])